version: '2'

services:

  base:
    image: node:11
    volumes:
      - .:/usr/src/service/
    working_dir: /usr/src/service/

  install:
    extends:
      service: base
    command: npm i

  integration:
    extends:
      service: base
    command: npm start
    ports:
      - 3333:3333

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile-wp
    restart: always
    links:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - .:/var/www/html/wp-content/themes/myTheme

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

